# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbG8Q--rijv6ebZ1nw02rb9yaBuO497P
"""

print('Dia berkata : "Pergilah!"')

print("Aku menimpali : \"Apakah kau ingin aku 'angkat kaki'?\"")

print("\\(^-^)/ (\\-__-/)")