# -*- coding: utf-8 -*-
"""manipulasi_string3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZHwgQvGxJOyg4L2W3T1AGPu0gonRiruD

# New Section
"""

template = 'Halo, saya %s dari %s'
print(template % ('Lendis Fabri', 'Indonesia'))
# output: Halo, saya Lendis Fabri dari Indonesia

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka manakan {} dan minum {}'

print(template.format(nama = 'Lendis Fabri', asal = 'Indonesia'))
print(template_2.format(nama = 'Nasi goreng', asal = 'Air Putih'))

nama = 'Lendis Fabri'
asal = 'Indonesia'
print(f'Perkenalkan saya {nama} dari {asal}')

alamat = 'Surabaya, Jawa Timur, Indonesia'
print(alamat.split())
# ['Surabaya', 'Jawa','Timur','Indonesia']
print(alamat.split(','))
# ['Surabaya', 'Jawa Timur','Indonesia']
print(alamat.split(', '))
# ['Surabaya', 'Jawa Timur','Indonesia']

print(' '.join(['aku', 'suka', 'phyton']))
# aku suka phyton
print(' '.join(alamat.split(', ')))
# Surabaya jawa Timur Indonesia

print('halo selamat pagi!'.upper())

print('Halo Selamat Pagi!'.lower())

print('halo selamat pagi!'.title())

print('hAlo SelamaT paGi!'.swapcase())

angka ='1234567'
print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))

Paragraf = 'Baru-baru ini ditemukan meteor di suatu sungai'

x = paragraf.count ('di')

print(f'Kata "di" muncul sebanyak {x} kali')

