# -*- coding: utf-8 -*-
"""Tipe Data Casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CJZTpFhCEvD6OiljiqQphZP0QgurCDK

Type Data Casting
"""

nama = 'Budi'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

"""Konversi Tipe Data"""

user = input('Masukkan usia anda: ')

print(type(usia))

panjang = input('Masukkan panjang: ')
lebar = input('Masukkan lebar: ')

print('Luas =', panjang * lebar)

panjang = int(input('Masukkan panjang: '))
lebar = float(input('Masukkan lebar: '))

print('Luas =', panjang * lebar)

a = 10

kata = 'Jeruk' * 5

print(kata)

nama = 'Wudi'
tahun_lahir = 2000
print(nama + ' lahir di tahun ' + str(tahun_lahir))